### ISSUE TITLE
twcmd_focus_after_closing does not seem to work

### ISSUE THREAD

**Issue by bbinet** [yssl/TWcmd.vim#1]
I was interested in twcmd.vim for its twcmd_focus_after_closing advertised feature, but it does not seem to work for me:
I have 2 tabs opened, the first tab has the focus: then I enter `:tabnew` which creates a new tab at the 2nd position, then when I close this newly created tab with `:q`, the last tab is focused while I was expecting to have the first tab focused.

Is this a bug or a configuration issue?

**Comment by yssl** [comment]
That feature only works when you close a tab or a window by `:TWcmd tcm q` or `:TWcmd wcm q`.
I couldn't find the way to hook Vim's closing commands, so I provided seperate commands for that purpose.

**Comment by bbinet** [comment]
for the record, I managed to get it work by following http://vim.1045645.n5.nabble.com/Tab-Order-td5708299.html#a5722304

**Comment by yssl** [comment]
Thank you for the information. I'll check it later since I'm so busy these days.
